---
title: "TIdyTuesdayKenyaCensus"
author: "Jeff Grayum"
date: "2/4/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading Libraries
```{r}
library(tidyverse)
library(tidytuesdayR)
library(scales)
library(ggthemes)
library(janitor)
```

Loading and cleaning datasets.
```{r}
tuesdata <- tidytuesdayR::tt_load('2021-01-19')

households <- tuesdata$households %>%
  clean_names() %>%
  mutate(county = str_trim(county),
         county = str_replace_all(county, "([a-z])([A-Z])", "\\1 \\2"))

crops <- tuesdata$crops %>%
  clean_names() %>%
  gather(crop, households, -sub_county, -farming) %>%
  filter(!is.na(households)) %>%
  mutate(county = str_to_title(sub_county)) %>%
  filter(county != "Kenya") 

gender <- tuesdata$gender %>%
  clean_names()
```

Starting with "gender" dataset.
```{r}
gender %>%
  filter(county != "Total") %>%
  mutate(county = fct_reorder(county, total)) %>%
  ggplot(aes(total, county)) +
  geom_col() +
  scale_x_continuous(labels = comma) +
  labs(x = "Population",
       y = "County",
       title = "Populations of Kenyan Counties",
       caption = "Source: rKenyaCensus") +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"))

gender %>%
  filter(county != "Total") %>%
  gather(gender, population, male, female, intersex) %>%
  mutate(county = fct_reorder(county, total, sum)) %>%
  ggplot(aes(population, county, fill = gender)) +
  geom_col() +
  scale_x_continuous(labels = comma) +
  labs(x = "Population",
       y = "County",
       fill = "Gender",
       title = "Populations of Kenyan Counties",
       caption = "Source: rKenyaCensus") +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"))

gender %>%
  filter(county != "Total") %>%
  mutate(pct_male = male / total) %>%
  arrange(desc(pct_male)) %>%
  ggplot(aes(total, pct_male)) +
  geom_point() +
  geom_text(aes(label = county),
            vjust = 1, hjust = 1) +
  geom_hline(color = "orange", yintercept = 0.5) +
  scale_x_continuous(labels = comma) +
  scale_y_continuous(labels = percent) +
  labs(x = "County population",
       y = "% male",
       title = "Percentage of male's in Kenyan counties",
       caption = "Source: rKenyaCensus") +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"))
```


```{r}
households %>%
  filter(county != "Kenya") %>%
  arrange(desc(average_household_size)) %>%
  ggplot(aes(population, average_household_size)) +
  geom_point() +
  geom_text(aes(label = county),
            vjust = 1, hjust = 1) +
  scale_x_log10(labels = comma) +
  expand_limits(y = 0) +
  labs(x = "County population",
       y = "Avg household size",
       title = "Average household size in Kenya, by county",
       caption = "Source: rKenyaCensus") +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"))
```

```{r}
crop_counties <- crops %>%
  mutate(county = fct_reorder(county, households, sum),
         crop = fct_reorder(crop, households, sum)) 

crop_counties %>%
  ggplot(aes(households, county, fill = crop)) +
  geom_col() +
  labs(x = "Number of households farming crop",
       y = "",
       fill = "Crop",
       title = "Farming in Kenyan counties",
       caption = "Source: rKenyaCensus") +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"))

crop_counties %>%
  complete(crop, county, fill = list(households = 0)) %>%
  ggplot(aes(crop, county, fill = households)) +
  geom_tile() +
  labs(x = "Crop",
       y = "",
       fill = "Number of households",
       title = "Farming in Kenyan counties",
       caption = "Source: rKenyaCensus") +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"),
        axis.text.x = element_text(angle = 90, hjust = 1))

crop_counties %>%
  inner_join(households, by = "county") %>%
  mutate(pct_households = households / number_of_households) %>%
  filter(crop == "avocado") %>%
  mutate(county = fct_reorder(county, pct_households)) %>%
  ggplot(aes(pct_households, county, sum)) + 
  geom_col() +
  labs(x = "% of households farming avocado",
       y = "County",
       title = "Which Kenyan counties produce the most avocado's?") +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman")) +
  scale_x_continuous(labels = percent)


```

